name: Build and Deploy NGINX

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nginx-app
  REGISTRY: docker.io
  REPO: yadav1590/nginx:nayra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REPO }}:latest

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REPO }}:latest
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Deploy StatefulSet to Kubernetes
      run: |
        kubectl apply -f ./nginx-statefulset.yaml
        kubectl rollout status statefulset nginx-stateful
